[package]
name = "test-cert-gen"
version = "0.7.0-pre"
authors = ["Stiopa Koltsov <stepan.koltsov@gmail.com>"]
edition = "2018"
description = "Utility to generate certificates for tests (e. g. for TLS)"
license = "MIT/Apache-2.0"

[lib]
bench = false

[dependencies]
tempdir = "0.3.7"
pem = "0.8.3"
