[package]
name = "tls-api-native-tls"
version = "0.3.0-pre"
authors = ["Stepan Koltsov <stepan.koltsov@gmail.com>"]
description = "TLS API implementation over native-tls crate"
license = "MIT/Apache-2.0"
repository = "https://github.com/stepancheg/rust-tls-api/"
keywords = ["tls"]
edition = "2018"

[badges]
travis-ci = { repository = "https://github.com/stepancheg/rust-tls-api/", branch = "master" }

[dependencies]
native-tls = "0.2"
tls-api = { path = "../api", version = "=0.3.0-pre" }

[dev-dependencies]
tls-api-test = { path = "../api-test", version = "=0.3.0-pre" }
