[package]
name = "interop"
version = "0.0.0"
authors = ["Stepan Koltsov <stepan.koltsov@gmail.com>"]
publish = false
edition = "2018"

[dependencies]
tls-api-test       = { path = "../api-test" }
tls-api-openssl    = { path = "../impl-openssl" }
tls-api-rustls     = { path = "../impl-rustls" }
tls-api-native-tls = { path = "../impl-native-tls" }
