[package]
name = "tls-api"
version = "0.2.1"
authors = ["Stepan Koltsov <stepan.koltsov@gmail.com>"]
description = "TLS API without implementation"
license = "MIT/Apache-2.0"
repository = "https://github.com/stepancheg/rust-tls-api/"
readme = "../README.md"
keywords = ["tls"]

[badges]
travis-ci = { repository = "https://github.com/stepancheg/rust-tls-api/", branch = "master" }

[dependencies]
log        = "0.4"
